### ISSUE TITLE
Error on converting javascript to coffee

### ISSUE THREAD

**Issue by BrahimDa** [nickdowse/RailsMagicClipboard#8]
When I paste a JavaScript in a ".coffee" file I get a blank error message, and it doesn't convert my code

**ScreenShot:**
![capture du 2015-11-20 14 36 32](https://cloud.githubusercontent.com/assets/3429115/11301144/fc1dd41a-8f94-11e5-9641-d42e9666fe07.png)

**Console Error:**
```
Error code: 1
error: 
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "RailsMagicClipboard in /home/ibrahim/.config/sublime-text-3/Installed Packages/Rails Magic Clipboard.sublime-package", line 119, in run
  File "/opt/sublime_text/sublime.py", line 115, in set_clipboard
    return sublime_api.set_clipboard(text)
TypeError: String required

```

**Comment by nickdowse** [comment]
Hey @BrahimDa, that's not good! Can you let me know the system details you're running it on (looks like Ubuntu to me, but including version number etc)? Also, does it happen every time? What happens if you try and paste in Sass to a .sass file or Haml to a .haml file?

**Comment by BrahimDa** [comment]
Hey @nickdowse, i'm runnig it on ubutnu 15.04, actually i have this bug only when i paste javascript. Sass and Haml work perfectly
